# This file was generated by GoReleaser. DO NOT EDIT.
cask "mdt" do
  version "0.1.1"

  on_macos do
    sha256 "9b99ff1a329141a606090a0e2ea74ec9d3822f1c03de7374f2418f2fee6e9d35"
    url "https://github.com/JosePBrotons/mobile-dev-tools/releases/download/v#{version}/mdt_#{version}_darwin_all.tar.gz"
  end

  name "mdt"
  desc "Installs mobile and Java development tools on macOS"
  homepage "https://github.com/JosePBrotons/mobile-dev-tools"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "mdt"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr",
                     args: ["-dr", "com.apple.quarantine", "#{staged_path}/mdt"]
    end
  end

  # No zap stanza required
end
